// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/ui/journal-viewer": {
    params: {};
  };
  "/ui/entry-viewer/:entryId": {
    params: {
      "entryId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/ui/journal-viewer" | "/ui/entry-viewer/:entryId" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/ui/journal-viewer.tsx": {
    id: "routes/ui/journal-viewer";
    page: "/ui/journal-viewer";
  };
  "routes/ui/entry-viewer.tsx": {
    id: "routes/ui/entry-viewer";
    page: "/ui/entry-viewer/:entryId";
  };
  "routes/catch-all.tsx": {
    id: "routes/catch-all";
    page: "/*";
  };
};